program: scripts/sweep_world_model.py
method: random
run_cap: 200
metric:
  name: world_model/val_mse
  goal: minimize
parameters:
  population_size:
    value: 1024
  group_size:
    value: 4
  weight_decay:
    value: 1e-5
  b1:
    value: 0.9
  sigma:
    distribution: uniform
    min: 0.001
    max: 0.1
  sigma_decay_rate:
    distribution: uniform
    min: 0.99999
    max: 0.999999
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.001
  num_epochs:
    values: [1250000]
